name: movie_api_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Các gói cần thiết khi ứng dụng chạy
  provider: ^6.1.2
  dio: ^5.4.3+1
  retrofit: ^4.1.0
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  video_player: ^2.9.1
  json_annotation: ^4.9.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Các gói chỉ cần cho việc phát triển và sinh code
  build_runner: ^2.4.10
  retrofit_generator: ^8.1.0
  json_serializable: ^6.9.0
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/